version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    network_mode: bridge
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
