version: "3"
services:
  redis:
    container_name: redis
    network_mode: bridge
    image: redis:alpine
    volumes:
      - ./datadir/redis:/data
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly yes"]
  mongodb:
    container_name: mongodb
    network_mode: bridge
    image: mongo
    volumes:
      - ./datadir/mongo:/data/db
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mariadb:
    container_name: mariadb
    network_mode: bridge
    build: ./mariadb-myrocks
    volumes:
      - ./datadir/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  postgre:
    container_name: postgre
    network_mode: bridge
    image: postgres:alpine
    volumes:
      - ./datadir/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  postgis:
    container_name: postgis
    network_mode: bridge
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - ./datadir/postgis:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  mysql:
    container_name: mysql
    network_mode: bridge
    image: mysql:5.7
    volumes:
      - ./datadir/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example