version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.6.0
    environment:
      - discovery.type=single-node
      - cluster.name=local-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro
    ports:
      - "9000:9000"
    restart: always
volumes:
  esdata:
    driver: local
