version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    network_mode: host
    image: elasticsearch:7.8.1
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./datadir/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"