version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.6.0
    environment:
      - "discovery.type=single-node"
      - "cluster.name=local-docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
  cerebro:
    container_name: cerebro
    image: lmenezes/cerebro
    ports:
      - "9000:9000"
    restart: always
  kibana:
    container_name: kibana
    image: kibana:7.5.1
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
  logstash:
    container_name: logstash
    image: logstash:7.5.1
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local
