version: "3"
services:
  nginx: 
    container_name: nginx
    image: nginx:alpine
    volumes: 
      - ./datadir/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80" 
    restart: always
    network_mode: "host"
