version: "3"
services:
  nginx-local: 
    container_name: nginx-local
    image: nginx:alpine
    volumes: 
      - ./datadir/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80" 
    restart: always
    network_mode: "host"
