# docker run --rm -it -v faktory-data:/var/lib/faktory -p 127.0.0.1:7419:7419 -p 127.0.0.1:7420:7420 contribsys/faktory:latest /faktory -b :7419 -w :7420 -e production

version: "3"
services: 
  faktory:
    container_name: faktory 
    image: contribsys/faktory:latest
    restart: always
    ports:
      - "127.0.0.1:7419:7419"
      - "127.0.0.1:7420:7420"
    volumes:
      - ./datadir:/var/lib/faktory