version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    network_mode: "host"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=localhost:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    network_mode: "host"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=localhost:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    network_mode: "host"

